"""phase2_step8_asset_classification

Revision ID: 393130548c7e
Revises: e559e9c6cf82
Create Date: 2026-05-11 11:41:40.681806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393130548c7e'
down_revision: Union[str, None] = 'e559e9c6cf82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.Enum('LAYER_1', 'LAYER_2', 'DEFI', 'INFRASTRUCTURE', 'GAMING', 'AI', 'MEME', 'STABLECOIN', 'EXCHANGE', 'OTHER', name='sector'), nullable=True))
        batch_op.add_column(sa.Column('chain', sa.Enum('BITCOIN', 'ETHEREUM', 'SOLANA', 'BNB_CHAIN', 'AVALANCHE', 'ARBITRUM', 'OPTIMISM', 'POLYGON', 'BASE', 'MULTI_CHAIN', 'OTHER', name='chain'), nullable=True))
        batch_op.add_column(sa.Column('market_cap_tier', sa.String(length=10), nullable=True, comment='MEGA / LARGE / MID / SMALL / MICRO'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('market_cap_tier')
        batch_op.drop_column('chain')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
