"""phase2_step1_strategies_table_and_order_strategy_fk

Revision ID: 54cae3e93f1f
Revises: 2b14dd712063
Create Date: 2026-05-11 10:36:09.189587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cae3e93f1f'
down_revision: Union[str, None] = '2b14dd712063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True, comment="Optional hex color for UI (e.g. '#25d9a7')"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', name=op.f('uq_strategies_name'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_strategy_id_strategies'), 'strategies', ['strategy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_strategy_id_strategies'), type_='foreignkey')
        batch_op.drop_column('strategy_id')

    op.drop_table('strategies')
    # ### end Alembic commands ###
