"""phase2_step5_trade_confirmations_table

Revision ID: 68609f4c1594
Revises: fc57f33d3f5f
Create Date: 2026-05-11 11:17:02.392911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68609f4c1594'
down_revision: Union[str, None] = 'fc57f33d3f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('sub_account_id', sa.String(length=36), nullable=False),
    sa.Column('sub_account_name', sa.String(length=120), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee_currency', sa.String(length=20), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('execution_venue', sa.String(length=40), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('strategy_name', sa.String(length=120), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('margin_used', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('linked_buy_order_id', sa.String(length=36), nullable=True),
    sa.Column('raw_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_trade_confirmations_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_confirmations'))
    )
    with op.batch_alter_table('trade_confirmations', schema=None) as batch_op:
        batch_op.create_index('ix_tc_confirmed', ['confirmed_at'], unique=False)
        batch_op.create_index('ix_tc_order', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_confirmations', schema=None) as batch_op:
        batch_op.drop_index('ix_tc_order')
        batch_op.drop_index('ix_tc_confirmed')

    op.drop_table('trade_confirmations')
    # ### end Alembic commands ###
