"""Initial schema (squashed from 9 phase migrations)

Revision ID: 6f0a088e63c1
Revises: 
Create Date: 2026-05-13 13:10:20.066117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0a088e63c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('asset_type', sa.Enum('CRYPTO', 'TOKEN', 'FUND', 'OTHER', name='assettype'), nullable=False),
    sa.Column('coingecko_id', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sector', sa.Enum('LAYER_1', 'LAYER_2', 'DEFI', 'INFRASTRUCTURE', 'GAMING', 'AI', 'MEME', 'STABLECOIN', 'EXCHANGE', 'OTHER', name='sector'), nullable=True),
    sa.Column('chain', sa.Enum('BITCOIN', 'ETHEREUM', 'SOLANA', 'BNB_CHAIN', 'AVALANCHE', 'ARBITRUM', 'OPTIMISM', 'POLYGON', 'BASE', 'MULTI_CHAIN', 'OTHER', name='chain'), nullable=True),
    sa.Column('market_cap_tier', sa.String(length=10), nullable=True, comment='MEGA / LARGE / MID / SMALL / MICRO'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=True)

    op.create_table('benchmark_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_prices')),
    sa.UniqueConstraint('symbol', 'date', name='uq_benchmark_symbol_date')
    )
    with op.batch_alter_table('benchmark_prices', schema=None) as batch_op:
        batch_op.create_index('ix_benchmark_symbol', ['symbol'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_currency', sa.Enum('USDT', 'USDC', name='basecurrency'), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('benchmark', sa.String(length=20), nullable=True),
    sa.Column('high_water_mark', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('management_fee_rate', sa.Numeric(precision=6, scale=4), nullable=True, comment='Annual management fee, decimal (0.02 = 2%)'),
    sa.Column('performance_fee_rate', sa.Numeric(precision=6, scale=4), nullable=True, comment='Performance fee above HWM, decimal (0.20 = 20%)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True, comment="Optional hex color for UI (e.g. '#25d9a7')"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', name=op.f('uq_strategies_name'))
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('equity_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_deposited', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('sub_account_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_equity_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equity_snapshots')),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_snapshot_portfolio_date')
    )
    op.create_table('manual_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('set_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_manual_price_history_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_price_history'))
    )
    with op.batch_alter_table('manual_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_price_history_asset_id'), ['asset_id'], unique=False)

    op.create_table('nav_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_nav', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('units_outstanding', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_unit', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('gross_exposure', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('net_exposure', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_nav_records_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_records')),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_nav_portfolio_date')
    )
    with op.batch_alter_table('nav_records', schema=None) as batch_op:
        batch_op.create_index('ix_nav_date', ['date'], unique=False)

    op.create_table('price_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('BINANCE', 'KUCOIN', 'COINGECKO', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_price_sources_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_sources')),
    sa.UniqueConstraint('asset_id', 'source_type', name='uq_source_per_asset')
    )
    op.create_table('sub_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('SPOT', 'FUTURES', name='subaccounttype'), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_sub_accounts_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_accounts'))
    )
    op.create_table('deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sub_account_id', sa.String(length=36), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', name='deposittype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sub_account_id'], ['sub_accounts.id'], name=op.f('fk_deposits_sub_account_id_sub_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deposits'))
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sub_account_id', sa.String(length=36), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='side'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction'), nullable=True),
    sa.Column('margin_used', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('funding_accumulated', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('linked_buy_order_id', sa.String(length=36), nullable=True),
    sa.Column('sell_quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_CLOSED', 'CLOSED', name='orderstatus'), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP_MARKET', 'STOP_LIMIT', 'TRAILING_STOP', 'UNKNOWN', name='ordertype'), nullable=True),
    sa.Column('execution_venue', sa.Enum('BINANCE_SPOT', 'BINANCE_FUTURES', 'OKX_SPOT', 'OKX_FUTURES', 'BYBIT_SPOT', 'BYBIT_FUTURES', 'KUCOIN_SPOT', 'KUCOIN_FUTURES', 'HYPERLIQUID', 'DERIBIT', 'DEX', 'OTC', 'MANUAL', name='executionvenue'), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('exchange_trade_id', sa.String(length=100), nullable=True),
    sa.Column('expected_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('fee_currency', sa.String(length=20), nullable=True),
    sa.Column('maker_taker', sa.Enum('MAKER', 'TAKER', 'UNKNOWN', name='makertaker'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_buy_order_id'], ['orders.id'], name=op.f('fk_orders_linked_buy_order_id_orders')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_orders_strategy_id_strategies')),
    sa.ForeignKeyConstraint(['sub_account_id'], ['sub_accounts.id'], name=op.f('fk_orders_sub_account_id_sub_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_exchange_order_id'), ['exchange_order_id'], unique=False)

    op.create_table('funding_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('funding_time', sa.DateTime(), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=24, scale=8), nullable=False, comment='position_size × mark_price × funding_rate × direction_sign — positive = paid'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_funding_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_payments'))
    )
    with op.batch_alter_table('funding_payments', schema=None) as batch_op:
        batch_op.create_index('ix_funding_order_time', ['order_id', 'funding_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_payments_order_id'), ['order_id'], unique=False)

    op.create_table('order_tags',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_tags_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_order_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'tag_id', name=op.f('pk_order_tags'))
    )
    op.create_table('trade_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('sub_account_id', sa.String(length=36), nullable=False),
    sa.Column('sub_account_name', sa.String(length=120), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee_currency', sa.String(length=20), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('execution_venue', sa.String(length=40), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('strategy_name', sa.String(length=120), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('margin_used', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('linked_buy_order_id', sa.String(length=36), nullable=True),
    sa.Column('raw_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_trade_confirmations_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_confirmations'))
    )
    with op.batch_alter_table('trade_confirmations', schema=None) as batch_op:
        batch_op.create_index('ix_tc_confirmed', ['confirmed_at'], unique=False)
        batch_op.create_index('ix_tc_order', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_confirmations', schema=None) as batch_op:
        batch_op.drop_index('ix_tc_order')
        batch_op.drop_index('ix_tc_confirmed')

    op.drop_table('trade_confirmations')
    op.drop_table('order_tags')
    with op.batch_alter_table('funding_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_payments_order_id'))
        batch_op.drop_index('ix_funding_order_time')

    op.drop_table('funding_payments')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_exchange_order_id'))

    op.drop_table('orders')
    op.drop_table('deposits')
    op.drop_table('sub_accounts')
    op.drop_table('price_sources')
    with op.batch_alter_table('nav_records', schema=None) as batch_op:
        batch_op.drop_index('ix_nav_date')

    op.drop_table('nav_records')
    with op.batch_alter_table('manual_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_price_history_asset_id'))

    op.drop_table('manual_price_history')
    op.drop_table('equity_snapshots')
    op.drop_table('tags')
    op.drop_table('strategies')
    op.drop_table('portfolios')
    with op.batch_alter_table('benchmark_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_benchmark_symbol')

    op.drop_table('benchmark_prices')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))

    op.drop_table('assets')
    # ### end Alembic commands ###
