"""phase2_step6_portfolio_enrichment

Revision ID: e1fd03ecb7a7
Revises: 68609f4c1594
Create Date: 2026-05-11 11:27:24.867826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fd03ecb7a7'
down_revision: Union[str, None] = '68609f4c1594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inception_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('benchmark', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('high_water_mark', sa.Numeric(precision=24, scale=8), nullable=True))
        batch_op.add_column(sa.Column('management_fee_rate', sa.Numeric(precision=6, scale=4), nullable=True, comment='Annual management fee, decimal (0.02 = 2%)'))
        batch_op.add_column(sa.Column('performance_fee_rate', sa.Numeric(precision=6, scale=4), nullable=True, comment='Performance fee above HWM, decimal (0.20 = 20%)'))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('performance_fee_rate')
        batch_op.drop_column('management_fee_rate')
        batch_op.drop_column('high_water_mark')
        batch_op.drop_column('benchmark')
        batch_op.drop_column('inception_date')

    # ### end Alembic commands ###
