"""phase2_step2_order_metadata_columns

Revision ID: f2d1995bcaa7
Revises: 54cae3e93f1f
Create Date: 2026-05-11 10:48:45.043460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d1995bcaa7'
down_revision: Union[str, None] = '54cae3e93f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP_MARKET', 'STOP_LIMIT', 'TRAILING_STOP', 'UNKNOWN', name='ordertype'), nullable=True))
        batch_op.add_column(sa.Column('execution_venue', sa.Enum('BINANCE_SPOT', 'BINANCE_FUTURES', 'OKX_SPOT', 'OKX_FUTURES', 'BYBIT_SPOT', 'BYBIT_FUTURES', 'KUCOIN_SPOT', 'KUCOIN_FUTURES', 'HYPERLIQUID', 'DERIBIT', 'DEX', 'OTC', 'MANUAL', name='executionvenue'), nullable=True))
        batch_op.add_column(sa.Column('exchange_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exchange_trade_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('expected_price', sa.Numeric(precision=24, scale=8), nullable=True))
        batch_op.add_column(sa.Column('slippage', sa.Numeric(precision=24, scale=8), nullable=True))
        batch_op.add_column(sa.Column('fee_currency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('maker_taker', sa.Enum('MAKER', 'TAKER', 'UNKNOWN', name='makertaker'), nullable=True))
        # server_default='0' so existing rows get a value during the ALTER
        # (SQLite refuses NOT NULL adds without a default). The ORM-level
        # default=False still applies to new rows; this is migration-only.
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_exchange_order_id'), ['exchange_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_exchange_order_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('maker_taker')
        batch_op.drop_column('fee_currency')
        batch_op.drop_column('slippage')
        batch_op.drop_column('expected_price')
        batch_op.drop_column('exchange_trade_id')
        batch_op.drop_column('exchange_order_id')
        batch_op.drop_column('execution_venue')
        batch_op.drop_column('order_type')

    # ### end Alembic commands ###
