"""phase2_step3_funding_payments_table

Revision ID: fc57f33d3f5f
Revises: f2d1995bcaa7
Create Date: 2026-05-11 11:04:15.781905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc57f33d3f5f'
down_revision: Union[str, None] = 'f2d1995bcaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('funding_time', sa.DateTime(), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=24, scale=8), nullable=False, comment='position_size × mark_price × funding_rate × direction_sign — positive = paid'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_funding_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_payments'))
    )
    with op.batch_alter_table('funding_payments', schema=None) as batch_op:
        batch_op.create_index('ix_funding_order_time', ['order_id', 'funding_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_payments_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_payments_order_id'))
        batch_op.drop_index('ix_funding_order_time')

    op.drop_table('funding_payments')
    # ### end Alembic commands ###
